# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.IntegerField(choices=[(1, 'inicio'), (2, 'menu'), (3, 'saludos')], default=1),
        ),
    ]
